<a href="https://colab.research.google.com/github/akash-ranjan8/MACHINE_LEARNING_MODELS_IN_PYTHON/blob/master/Combined_Cycle_Power_Plant_using_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Artifical Neural Network

#Combined Cycle Power Plant Dataset

#Importing the libraries

In [12]:
import numpy as np
import pandas as pd
import tensorflow as tf

#Importing the dataset

In [13]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,-1].values
print(X)
print(Y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


#Splitting the dataset into the training set and the test set

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)
print(X_train)
print(X_test)
print(Y_train)
print(Y_test)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]
[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]
[473.93 467.87 431.97 ... 459.01 462.72 428.12]
[431.23 460.01 461.14 ... 473.26 438.   463.28]


#Building the ANN

Initializing the ANN

In [15]:
ann = tf.keras.models.Sequential()

Adding the input layer and the first hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the second hidden layer

In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the Output layer

In [18]:
ann.add(tf.keras.layers.Dense(units=1))

#Training the ANN

Compiling the ANN

In [19]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

Training the ANN on the training dataset

In [20]:
ann.fit(X_train, Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 0s 874us/step - loss: 16718.5684
Epoch 2/100
240/240 [==============================] - 0s 829us/step - loss: 217.4365
Epoch 3/100
240/240 [==============================] - 0s 860us/step - loss: 212.2060
Epoch 4/100
240/240 [==============================] - 0s 817us/step - loss: 205.9631
Epoch 5/100
240/240 [==============================] - 0s 865us/step - loss: 198.2993
Epoch 6/100
240/240 [==============================] - 0s 903us/step - loss: 189.4965
Epoch 7/100
240/240 [==============================] - 0s 876us/step - loss: 180.0124
Epoch 8/100
240/240 [==============================] - 0s 867us/step - loss: 169.7489
Epoch 9/100
240/240 [==============================] - 0s 824us/step - loss: 158.9460
Epoch 10/100
240/240 [==============================] - 0s 899us/step - loss: 147.5976
Epoch 11/100
240/240 [==============================] - 0s 926us/step - loss: 135.9520
Epoch 12/100
240/240 [============================

#Predicting the test set results

In [21]:
Y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[430.36 431.23]
 [461.48 460.01]
 [465.02 461.14]
 ...
 [472.17 473.26]
 [439.16 438.  ]
 [458.29 463.28]]
